### PR TITLE
[14.0] Use GitHub actions instread of travis

### PR DESCRIPTION
**Pull request by sbidoul**
For anyone interested this is roughly how it will look like. Comments welcome, of course.

### CODE REVIEW

**Comment by HaraldPanten** [comment]
Why these changes? Just to know... 🤔

**Comment by sbidoul** [comment]
Because travis is now expensive so we are going to progressively replace it. This is a step the implementation of what I announced on the contributors mailing list a while ago.

**Comment by sbidoul** [comment]
Waiting for https://github.com/OCA/reporting-engine/pull/516 to resolve the development status check error.

**Comment by HaraldPanten** [comment]
> Because travis is now expensive so we are going to progressively replace it. This is a step the implementation of what I announced on the contributors mailing list a while ago.

So... it would be implemented in all repositories

THX, Stéphane!

**Comment by sbidoul** [comment]
> So... it would be implemented in all repositories

Yes, I'm close to deploying this on the 14.0 branch of all repos. I'm just hesitating if we need a special feature in the merge bot to allow red builds on (some) github actions in a transition period.

**Comment by sbidoul** [comment]
And, BTW, here we have the much overdue license compatibility check, as well as the development status compatibility check.

**Comment by sbidoul** [comment]
.pot update work with GitHub actions https://github.com/OCA/mis-builder/commit/b1e9158a3e9180f300a376566585881377d2c154

**Pull request merged**
