### PR TITLE
[16.0][MIG] mis_builder_budget: Migration to 16.0

### PR DESCRIPTION
**Pull request by dzungtran89**
Needs:
- https://github.com/OCA/mis-builder/pull/472

### CODE REVIEW

**Review by Camille0907 — COMMENTED** [review]
Looks technically good, but please fix CI :)

**Review by Camille0907 — APPROVED** [review]

**Comment by sbidoul** [comment]
Thanks! Can you send this as a PR to acsone:16.0-mig-mis_builder-ape. It will be easier to test everything together.

**Comment by dzungtran89** [comment]
> Thanks! Can you send this as a PR to acsone:16.0-mig-mis_builder-ape. It will be easier to test everything together.

@sbidoul the PR has been created to the target branch

**Comment by StephaneMangin** [comment]
For the PR dependency, please take in account this comment https://github.com/OCA/edi/pull/724#issuecomment-1461765822

**Comment by dzungtran89** [comment]
Hi @StephaneMangin , the dependency has already included in this [commit](https://github.com/OCA/mis-builder/pull/488/commits/dfcbb9f6f79fbe8cc0f62b482c505fe34dfddbb2)

**Comment by sbidoul** [comment]
mis_builder_budget is now included in #472, so closing this one.

**Pull request closed without merging**
