### PR TITLE
[12.0] staging for version 3.6

### PR DESCRIPTION
**Pull request by sbidoul**
Migration of #266

### CODE REVIEW

**Comment by rvalyi** [comment]
Hello, @sbidoul 
thanks for this update. I'm not sure how your analytic filter works exactly, but what I know is that sometimes in a balanced double accounting move, the analytic account is carried on the other leg from the account.move.line you want to filter (I had this issue when selling projects). Do you see some workaround for such cases?

**Comment by sbidoul** [comment]
@rvalyi not sure what you mean. Does not seem related to this PR though. Can you open an issue with an example?

**Comment by fclementic2c** [comment]
LGTM
:+1:

**Pull request merged**
