### PR TITLE
[12.0][DEL] Old migration scripts

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by hbrunn — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Hahaha, we are synchronized

**Comment by pedrobaeza** [comment]
I delete my branch

**Comment by hbrunn** [comment]
so, I'm curious, will our ocabots collide?

**Comment by hbrunn** [comment]
can't we have them run against each other? depending on the server farm voodoo one will win

**Comment by pedrobaeza** [comment]
Yeah, it would be a curious test on how Travis deals with queues, but I'm afraid I have deleted it before reading your comment.

**Pull request merged**
