### PR TITLE
[FIX] report_id required on new KPI

### LINKED ISSUE #18: need to save report template before adding the first KPI
When creating a new report, it is necessary to save it before adding the first KPI, otherwise an error occurs when attempting to save the new KPI, because the report_id field is not initialized.

### PR DESCRIPTION
**Pull request by richard-willdooit**
When adding a new KPI to an unsaved report, the report_id is required and fails on the popup.

Fixes #18

### CODE REVIEW

**Review by adrienpeiffer — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
Please change module version number

**Comment by sbidoul** [comment]
Merging on 10.0 as it is a bugfix.

**Comment by sbidoul** [comment]
Merged at https://github.com/OCA/mis-builder/commit/3887de819dccd6955c1406924b4d4ae790d7f70c

**Pull request closed without merging**
