### PR TITLE
[14.0][IMP] add: css sticky table header added for mis-builder-widget

### PR DESCRIPTION
**Pull request by dora-jurcevic**
Hello ! 
Here is the modification of the CSS of the table header on mis-builder preview, making the header stick on the top of the page. Only CSS has been modified. 
Thank you in advance for the review,
This is my first PR, so please be gentile :)

### CODE REVIEW

**Review by sbidoul — APPROVED** [review]
Nice! Tested on runboat :+1:

**Comment by vdewulf** [comment]
Tested in runboat, the budget report is very long and when I scroll down, the column titles remain visible.
Cf. screeshot.
Selection_450
Thanks @dora-jurcevic !

**Review by vdewulf — APPROVED** [review]
Tested in runboat (see previous comment).
Functionally Approved!

**Comment by dora-jurcevic** [comment]
Wow, this was quick ! I am sure it's all part of the new welcome package for OCA newbies ;) 
Special thanks to @bguillot who helped me with the PR

**Comment by sbidoul** [comment]
/ocabot merge patch

Do you plan to port this to 16?

**Comment by dora-jurcevic** [comment]
> /ocabot merge patch
> 
> Do you plan to port this to 16?

Yes ! Next step, the same feature on V16 !

**Comment by pedrobaeza** [comment]
And v15, please

**Comment by vdewulf** [comment]
> > /ocabot merge patch
> > Do you plan to port this to 16?
> 
> Yes ! Next step, the same feature on V16 !

@dora-jurcevic hello, I was wondering if this was in V15 / V16? I don't see the corresponding PR here (or is it something still todo?). Thanks!

**Comment by sbidoul** [comment]
It is merged in 15 (https://github.com/OCA/mis-builder/pull/610#issuecomment-2466814114) but for 16 it needs to be done differently.

**Comment by vdewulf** [comment]
> It is merged in 15 ([#610 (comment)](https://github.com/OCA/mis-builder/pull/610#issuecomment-2466814114)) but for 16 it needs to be done differently.

Thanks! For v16, my accounting company is willing to pay someone to take care of this, if someone wants to make an offer.

@victor-champonnois @dora-jurcevic you might be interested in taking this task?

**Comment by sbidoul** [comment]
My dream is vertical scroll with headers row frozen, and horizontal scroll with kpi names column frozen :)

**Pull request merged**
