### PR TITLE
[14.0][FIX] mis_builder: fix access right issues when using actions

### PR DESCRIPTION
**Pull request by sebalix**

### CODE REVIEW

**Comment by sbidoul** [comment]
The code looks better indeed, but do you care explaining what this actually fixes ?

Do you think this should work as is on other Odoo versions?

**Review by i-vyshnevska — APPROVED** [review]

**Comment by i-vyshnevska** [comment]
@sbidoul direct access to "ir.actions.act_window" is allowed only for admin since v14, now access to action should be done  through the method "_for_xml_id"

**Comment by sbidoul** [comment]
Thanks for the explanation, @i-vyshnevska. LGTM.
Could you add a readme/newsfragments/410.bugfix with a one liner end-user oriented changelog entry?

**Review by yankinmax — APPROVED** [review]

**Comment by sebalix** [comment]
@sbidoul done, but regarding the `get_wizard_report_action` method I didn't find where this method is used so I didn't mention this part in the changelog entry.

**Comment by yankinmax** [comment]
@sbidoul maybe we should also port these fixes to v15?

**Comment by sbidoul** [comment]
Thanks for the fix!

**Pull request merged**
