### PR TITLE
[DO NOT MERGE] Check git repo

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
This might be a hint:

image

@pedrobaeza @simahawk @rousseldenis @etobella

**Comment by pedrobaeza** [comment]
Check https://github.com/actions/checkout/issues/766

**Comment by pedrobaeza** [comment]
It's saying about adding this in a previous step:

`git config --global --add safe.directory "$GITHUB_WORKSPACE"`

**Comment by sbidoul** [comment]
I dd this: https://github.com/OCA/oca-ci/commit/4b2f496eda62bfbf7512049df426a79c7215ebd2
Just need to wait for oca/oca-ci images to rebuild.

**Comment by pedrobaeza** [comment]
Thanks for the quick reaction. I'll try later on any of the failing branches

**Pull request closed without merging**
