### PR TITLE
[9.0][IMP] instance-level option to disable account expansion

### PR DESCRIPTION
**Pull request by pedrobaeza**
@Tecnativa

### CODE REVIEW

**Comment by sbidoul** [comment]
Thanks! I don't take this one as is, as I'll do a git merge of 10 in 9 and 11 later this week.

**Comment by pedrobaeza** [comment]
OK, then I will keep this PR opened meanwhile for being used in my instances through your excellent git-aggregator tool :wink:

**Comment by pedrobaeza** [comment]
@sbidoul have you performed the update on the other branches?

**Comment by sbidoul** [comment]
@pedrobaeza not yet I'll try to do it on Wednesday.

**Comment by sbidoul** [comment]
This is now on the 9.0 branch. Thanks!

**Pull request closed without merging**
