### PR TITLE
[13.0][ADD] mis_builder: allow to filter by analytic account group

### PR DESCRIPTION
**Pull request by benwillig**
New filter on analytic account group

### CODE REVIEW

**Comment by sbidoul** [comment]
@benwillig thanks! Code looks good to me.

Could you add a test (`test_analytic_filters.py` should hopefully be easy to extend with that). And add a file named `320.feature` in newsfragments, with a short changelog entry.

@sanrav can you test on runbot?

**Comment by sanrav** [comment]
Testing ok

**Review by HaraldPanten — APPROVED** [review]
Tested on Runbot and it seems to be working fine 👍

**Review by hbrunn — APPROVED** [review]
thanks, with the tests @sbidoul mentions

**Comment by apineux** [comment]
@baimont The file named 320.feature in newsfragments, with a short changelog entry is missing. Can you add it to complete this PR. Thanks

**Comment by baimont** [comment]
> @baimont The file named 320.feature in newsfragments, with a short changelog entry is missing. Can you add it to complete this PR. Thanks

done :-) thanks @apineux

**Review by apineux — APPROVED** [review]

**Comment by sbidoul** [comment]
Thanks for adding the test, @baimont !

**Review by sbidoul — APPROVED** [review]
I fixed the last lint error.

**Comment by rvalyi** [comment]
thank you for this feature!

**Review by LoisRForgeFlow — APPROVED** [review]
Works fine! :+1:

**Comment by sbidoul** [comment]
Thanks everyone for the contrib, reviews and tests. I backported to v12 in #346 and cherry-picked to #325 for the v14 migration.

**Pull request merged**
