### PR TITLE
[10.0][DOC] Add MIS documentation for Sphinx

### PR DESCRIPTION
**Pull request by elicoidal**
Suggestion welcome on filenames and structure

### CODE REVIEW

**Comment by sbidoul** [comment]
@elicoidal Thanks a lot! Overall I like it. I'll do a deeper review soon.

FWIW, I gave a MIS builder training this week with the following table of contents, which worked rather well:

* Intro: type of reports supported by MIS Builders
* Distinction between Templates and Instances
* Quick start: building a simple P&L report
* Instances example, column types
* Displaying reports
  * Preview, Drilldown
  * Excel, PDF exports
  * adding reports to the dashboard
* Accounting Expressions
  * bal, crd, deb
  * Modes (p, i, e)
  * Account selectors
  * Move line filters
* Expansion of Account Detail
* Python expressions basics
  * Arithmetic Expressions
  * Conditional Expressions
* Zero vs no data, AccountingNone
* Reporting on non-accounting data (queries)
* Styles
* Analytic Filters
* Data sources for columns
  * Actuals
  * Actuals (alternative): example, commitments
  * Sum/Difference
* MIS Budgets
* Sub KPI
  * Example building a trial balance with initial, debit, credit, ending balance over several periods

You may want to see if there are missing parts in your text, and add TODO entries so as to facilitate further contributions by others. (if you're reaching your patience limit, I'll do it :)

**Comment by elicoidal** [comment]
@sbidoul please check it out. Probably far from perfect as the original structure was not all compatible but that is a start.
Fill free to continue from here :smile:

**Comment by JordiBForgeFlow** [comment]
If it os ok I will review the doc and possibly improve, aiming use as
presentation during the Jornadas in Sevilla

**Comment by sbidoul** [comment]
@jbeficent sure, all help is welcome.

**Comment by sbidoul** [comment]
This is a very very good start. I merge it so more people can read it and contribute.

**Pull request merged**
