### PR TITLE
Forward port 10.0 to 12.0 [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by sbidoul**
This contains everything from 10.0 except the js part of the analytic filters.

This branch will become 12.0.

### CODE REVIEW

**Comment by sbidoul** [comment]
@njeudy here it is

**Comment by njeudy** [comment]
@sbidoul will check this

**Comment by elicoidal** [comment]
I tried to force rebuild 2 times the runbot without success.
@njeudy ?

**Comment by sbidoul** [comment]
@elicoidal runbot looks ready now.

**Comment by elicoidal** [comment]
@sbidoul thanks: I will have a quick functional test

**Comment by elicoidal** [comment]
@sbidoul light functional check, no issue so far (I am not sure about the budget calculation though: 2000 input for 12 months):

image

**Comment by sbidoul** [comment]
@elicoidal unfortunately buildbot has killed your db already.

Anyway, since the calculation algorithm should not be impacted by the Odoo version, if there is a bug for that it's present in other versions too. So I'll merge these 11 and 12 branches and we can dig this later.

Thanks for the review!

**Comment by sbidoul** [comment]
merged manually at 5c2e095294e95b69490f173d49becf223ec60259

**Comment by pedrobaeza** [comment]
Thanks!

**Pull request closed without merging**
