### PR TITLE
Version 3.1

### PR DESCRIPTION
**Pull request by sbidoul**
This is the integration branch that will become version 3.1. 

Everything here has been reviewed in [separate PR's](https://github.com/OCA/mis-builder/milestone/2?closed=1).

See [changelog](https://github.com/OCA/mis-builder/pull/33/files#diff-45868279802e9dac0162d9042ab7cf83).

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Comment by sbidoul** [comment]
@Martronic-SA @richard-willdooit  @jbeficent would you have some time to test this branch along with #38 and #40 ?

Then we'll do #39 and we can release 3.1.

I may postpone #24 to 3.2.

**Comment by richard-willdooit** [comment]
I should be able to look today - Cheers!

**Comment by richard-willdooit** [comment]
@sbidoul A minor thing, only for local testing, and not in this code....

But, my db that I am working with is set up for AU and not US, so all of the test_rendering fails as

`        self.lang = self.env['res.lang'].search([('code', '=', 'en_US')])[0]
`

returns an empty record set - it may be worth changing it to:

`        self.lang = self.env['res.lang'].search(
            [('code', '=', 'en_US'),
             '|',
             ('active', '=', True),
             ('active', '=', False)
             ])[0]
`

for completeness....

**Comment by richard-willdooit** [comment]
Produces results as I would expect with my multi-company test data.

**Review by richard-willdooit — APPROVED** [review]
Looks good to me.  Produces results as I would expect with my multi-company test data.

**Comment by sbidoul** [comment]
@richard-willdooit does https://github.com/OCA/mis-builder/pull/33/commits/d1caabccef6beb7bf70763bda086ff6e9042b686 address your remark https://github.com/OCA/mis-builder/pull/33#issuecomment-339184083 ?

**Comment by richard-willdooit** [comment]
@sbidoul Yes. Great

**Comment by sbidoul** [comment]
This one is ready for final testing. Everything has been reviewed already in separate PRs. Last minute comments are welcome, of course.

If there are no further remarks I'll merge in a few days.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: New features detailed in the change-log tested successfully

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
