### PR TITLE
[10.0] staging for version 3.6

### PR DESCRIPTION
**Pull request by sbidoul**
- [x] 9.0 is now in maintenance mode
- [x] some refactoring (#258)
- [x] Budget by account (similar to account_move_budget, but works with periods, ~~and allow a combined budget on KPIs and accounts~~) (#259)
- [x] Sub reports (use KPIs from other reports #155, #256)
- [x] Column-level analytic filters (#138, #261)

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]
Functional review :+1: 

Nice added features!

**Comment by sbidoul** [comment]
Travis-ci.org is having problems atm. Migrated this repo to travis-ci.com and retried.

**Pull request merged**
