### PR TITLE
[13.0] MIS Builder 4.0 staging

### PR DESCRIPTION
**Pull request by sbidoul**
Preparing release 4.0

### CODE REVIEW

**Review by HaraldPanten — APPROVED** [review]
Functional review. Bugfixes and features seem to be OK.

**Comment by JordiBForgeFlow** [comment]
@ChrisOForgeFlow

**Comment by TeoGoddet** [comment]
Functional review, particularly on budgets, works perfectly !
Also looked at the code and did not see problems.

**Review by TeoGoddet — APPROVED** [review]
Functional review, particularly on budgets, works perfectly !
Also looked at the code and did not see problems but i'm relatively new to odoo

**Review by ChrisOForgeFlow — APPROVED** [review]
LGTM

**Comment by sbidoul** [comment]
Thanks for the reviews ! I'll merge and port to 14 soon.

**Comment by sbidoul** [comment]
Oof, that was fast, I was prepared to wait an hour :laughing:

**Comment by sbidoul** [comment]
The port to 14.0 is in #400, in case anyone wants to do a quick test before merging.

**Pull request merged**
