### PR TITLE
[13.0] multi company improvements

### LINKED ISSUE #379: [13.0][14.0] mis_builder : Don't supports concurrent multicompany selection
This domain prevents the selection of several companies according to the use of concurrent multicompany implemented as of v13:
https://github.com/OCA/mis-builder/blob/bfa6677b57491156cbb8c6d1cc16b972fed01f36/mis_builder/views/mis_report_instance.xml#L175
**Simply change...**
¿Can be removed this domain?

**More ambitious change...**

Given the new scenario, can we consider keeping only one of the fields company (query_company_ids) and remove others (company_id and company_ids)?
https://github.com/OCA/mis-builder/blob/bfa6677b57491156cbb8c6d1cc16b972fed01f36/mis_builder/models/mis_report_instance.py#L590-L596
https://github.com/OCA/mis-builder/blob/bfa6677b57491156cbb8c6d1cc16b972fed01f36/mis_builder/models/mis_report_instance.py#L580-L588

### PR DESCRIPTION
**Pull request by sbidoul**
This is #327 with the the few improvements I suggested in review comments.

@MiquelRForgeFlow @JordiBForgeFlow let me know what you think.

closes #379 
closes #327

### CODE REVIEW

**Comment by sbidoul** [comment]
Looks like this bot message about maintainers is not working as exepected, as I am a maintainer...

**Review by carlosdauden — APPROVED** [review]
Thanks for your work!

**Comment by sbidoul** [comment]
@MiquelRForgeFlow @JordiBForgeFlow have you had a chance to look at this followup to your previous PR ?

**Comment by MiquelRForgeFlow** [comment]
@LoisRForgeFlow

**Review by LoisRForgeFlow — APPROVED** [review]
Hey, sorry for the long delay here... I have tested and the changes are added are perfectly fine with me. Thanks :+1:

**Pull request merged**
