### PR TITLE
[IMP] Allow referencing subkpis by name in expressions

### LINKED ISSUE #114: Allow writing `kpi_x.subkpi_y` in an expression

### PR DESCRIPTION
**Pull request by sbidoul**
closes #114

### CODE REVIEW

**Comment by sbidoul** [comment]
@sanrav would you like to test this on runbot? This should resolve your issue.

**Comment by sanrav** [comment]
Tested and everything is fine. Thanks !

**Comment by fclementic2c** [comment]
cool. any chance that add this new syntax in the expression helper ?

**Comment by sbidoul** [comment]
@fclementic2c done

**Comment by sbidoul** [comment]
This has been tested by @sanrav, and test coverage is good. Merging.

**Pull request merged**
