### PR TITLE
Resolve a couple of flake8 warnings

### PR DESCRIPTION
**Pull request by sbidoul**
- E722 bare except
- E742 ambiguous variable name

### CODE REVIEW

**Review by adrienpeiffer — APPROVED** [review]
:+1:

**Review by pedrobaeza — APPROVED** [review]

**Comment by sbidoul** [comment]
Thanks @pedrobaeza ! 

Could you refrain from merging in this repo? No harm done of course, but I think core maintainers and board members should use their super merging power only as a backup of repo maintainers or for administrative and maintenance purposes.

It may not be applicable everywhere, but here we have goal to stay on top of the backlog.

Reviews and contributions of all kind remain more than welcome of course!

**Comment by pedrobaeza** [comment]
I don't understand why. This is an "administrative" PR not changing functionality and greenifying the branch. Why should I refrain?

**Comment by sbidoul** [comment]
As I said, no harm done.  I just think we must reinforce maintainer responsibility, and it starts by progressively clarifying roles.

**Comment by pedrobaeza** [comment]
Well, considering that you are for now the only maintainer of this repository, I see that goal difficult to achieve, even if I agree, but it's just not the moment for it.

I see a perceiving rising of an evil aura around my person, when I'm only a "Getting things done" person, but I have to admit that with a remarkable [better to beg for forgiveness than to ask for permission](https://bothsidesofthetable.com/it-s-better-to-beg-for-forgiveness-than-to-ask-for-permission-97f5ad901371?gi=a067ffca97f0).

**Comment by sbidoul** [comment]
Evil? No certainly not! What you do is fantastic. Sorry if I offended you. 

My point is simply we want to give more emphasis on the responsibility of repo maintainers, and for that we need to clarify roles between them and core maintainers.

So in repos where there are dedicated maintainers who stay on top of their backlog like here, core maintainers should in general not intervene unless there is some administrative work to do or a conflict to resolve.

**Comment by pedrobaeza** [comment]
OK, no worries, thanks for clarifying.

Then please enroll more people in this repository maintenance. @jbeficent is a good candidate and a couple of your guys that have contributed to the project can be others.

**Pull request merged**
