### PR TITLE
Instance-level option to disable account detail expansion

### LINKED ISSUE #74: Instance-level toggle for Display detail by account
On mis.report.instance, add a flag `no_auto_expand_accounts` that disables expansion of account details for all kpis.

This should allow the creation of templates that have account expansion on by default, while disabling it on specific reports that use the template.

cc/ @jbeficent

### PR DESCRIPTION
**Pull request by sbidoul**
Closes #74

### CODE REVIEW

**Comment by sbidoul** [comment]
@jbeficent

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Tested in https://github.com/OCA/l10n-spain/pull/826

**Comment by sbidoul** [comment]
@benwillig @gva-acsone this may be of interest to you

**Review by pedrobaeza — APPROVED** [review]
Working flawlessly! Thanks, Stéphane.

About the new page, do you think it's a good idea to have it for 2 options?

**Comment by sbidoul** [comment]
@pedrobaeza there will be more in that page in the future (eg from #42 and #82)

**Comment by pedrobaeza** [comment]
OK, I see.

**Pull request merged**
