### PR TITLE
[IMP] mis_builder_budget: allow Analytic Accounts on account budget

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by sbidoul** [comment]
This makes sense to me.  

Out of curiosity, how do you use that in practice in actual reports? Or does that require additional custom modules to be of practical use?

**Comment by dreispt** [comment]
No additional modules needed.
With this you can add filters to your MIS Reports, that then can apply to both Account Moves and Budget Items, to have reports by Analytic Account.

**Comment by sbidoul** [comment]
Ah yes, the analytic mixin now provides a search function. Nice!

**Review by sbidoul — APPROVED** [review]

**Pull request merged**
