### PR TITLE
[13.0][FIX] mis_builder_budget: incorrect budget by account multi company rules.

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Probably missed during migration.

@ForgeFlow

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Comment by LoisRForgeFlow** [comment]
@sbidoul could you have a look? maybe this one can be merged.

**Comment by sbidoul** [comment]
@LoisRForgeFlow yes, looks good. Would be cool if you could add a "347.bugfix" newsfragment.

**Comment by LoisRForgeFlow** [comment]
@sbidoul newsfragment added.

**Comment by sbidoul** [comment]
Thanks!

/ocabot merge patch

**Comment by sbidoul** [comment]
cherry-picked on the 14.0 migration branch

**Pull request merged**
