### PR TITLE
[ADD] column-level analytic filters

### LINKED ISSUE #138: Analytic filter in report columns definition
I have a question,
is it possible if i have a kpi lines and want to display the total for each analytic account together as columns?, I mean each analytic account as a column in the report and displayed together and then put other period data as second row as the comparison such as below :

KPI and period                           analytic acc-1      analytic acc-2 analytic acc-3  ..and so on     Total

expenses                                   total an-acc-1      total-an-acc2  Total-an-acc3  ...and son       Total
expenses other period               total an-acc-1-op   ...........             ................... 

How to achieve this if it is possible with current state of mis-builder. Thank you

### PR DESCRIPTION
**Pull request by sbidoul**
Closes #138

### CODE REVIEW

**Review by HaraldPanten — COMMENTED** [review]
`ValueError: Invalid leaf analytic_account_id`

When setting an analytic account in any of the columns and trying to preview the report

**Comment by sbidoul** [comment]
@HaraldPanten have you tested on runbot (if yes, provide the link, please)? Do you have budget columns in the report?

**Comment by HaraldPanten** [comment]
Hi @sbidoul 

http://3410600-261-e31a06.runbot2-3.odoo-community.org/web#id=1&view_type=form&model=mis.report.instance&menu_id=213&action=316

Check column "M". Did I miss something?

**Comment by sbidoul** [comment]
> Did I miss something?

Certainly not, a stack trace is a bug. Thanks for testing and reporting, I'll look into it soon.

**Comment by sbidoul** [comment]
@HaraldPanten can you try again?

**Comment by HaraldPanten** [comment]
Hi @sbidoul 

check http://3410651-261-bbc0d0.runbot3.odoo-community.org/web?debug=1#id=1&view_type=form&model=mis.report.instance&menu_id=125&action=316

Column "M" --> In the preview mode, totals are being shown on column even if they've not analytic account.

Once you check the details of the  $64,999.99 amount, you can see that not all the entries belong to the same AA.

Only the entries in "Agrolait - Agrolait" AA should be taken in consideration, right?

**Comment by sbidoul** [comment]
Yes, that's how it works. I have put Agrolait in column M and you see $50,000.

**Review by HaraldPanten — APPROVED** [review]
Now it seems to be perfect . Functional review 👍

**Comment by sbidoul** [comment]
I'm merging this to the 3.6 staging branch. People interested in testing this furthen can do it via #254.

/ocabot merge

**Review by fclementic2c — COMMENTED** [review]
Functional test ok

**Pull request merged**
